app = "ppt-live"
primary_region = "bom"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  REDIS_URL = "rediss://default:gQAAAAAAAfdCAAIgcDE0ODA2NjNlN2U3YWQ0Mjc5YWQwNDgxNjdjMzIxZTI1Ng@smiling-panda-128834.upstash.io:6379"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
